steps:
  build-web:
    image: silex/emacs:alpine-ci
    when:
      branch: [ master ]
    secrets: [ cloudflare_account_id, cloudflare_api_token, repo_token ]
    commands: |
      apk add nodejs npm
      ./publish.sh
