#+title: Packaging GNU Guix for Void Linux
#+subtitle: System Crafters Live - April 12, 2024
#+date: [2024-04-12 Fri]
#+video: AxQU5aHWKRo

* News

- Hands-On Guile Scheme for Beginners, April Edition is now open for registration!

  https://systemcrafters.net/courses/hands-on-guile-scheme-beginners/

  There's a 10% discount until *6AM UTC, Monday April 15*!

- Guile Hoot 0.4.0 has been released!

  https://spritely.institute/news/guile-hoot-v040-released.html

- Join the System Crafters Craftering:

  https://codeberg.org/SystemCrafters/craftering

- System Crafters Newsletter Issue #009 is out!

  Read it here: https://systemcrafters.net/newsletter/sc-news-009
  Subscribe here: https://systemcrafters.net/newsletter/

* System Crafters Music?

Songs generated by crafters using a tool called Suno:

- [[https://suno.com/song/63ffc028-29e7-4dc0-b80c-ae595072f041/][Code Warriors]] by Thanos
- [[https://suno.com/song/0f22ca17-47fc-474e-8afe-fec78be20863/][Code Breaker]] by Thanos
- [[https://suno.com/song/39f02b78-af2c-4d66-9fdd-d6feb9fb912d/][System Slaughter]] by Benoit

* Packaging Guix for Void Linux

Today we're going to try and package Guix for Void Linux.  It has been tried before, but never got merged.

We'll try to carry forward the efforts already made by others to get Guix packaged for Void and see what we can learn along the way.

Existing work:

- Guile 3: https://github.com/void-linux/void-packages/pull/27320
- Guix: https://github.com/void-linux/void-packages/pull/22359

You can check out my personal package fork here:

https://github.com/daviwil/void-packages/
