#+title: Wiring Claude Code Into Emacs
#+subtitle: System Crafters Live - August 22, 2025
#+date: [2025-08-22 Fri]
#+video: 3N5FVSSQGYs

* News

- EmacsConf 2025 Call for Proposals deadline is September 19th!

  The conference will be December 6-7
  Submit your talk ideas at emacsconf.org/2025/submit/

- Emacs 30.2 has been released!

  This is a bugfix release but...  what does it fix??

  https://cgit.git.savannah.gnu.org/cgit/emacs.git/log/etc/NEWS?h=emacs-30

- Steve Yegge (yes, that one) has written a new AI agent package for Emacs, "efrit"

  https://github.com/steveyegge/efrit

* Wiring Claude Code Into Emacs

Today we will explore integrating Claude Code into an Emacs workflow and tackle the challenges of using it within terminal emulators like =eat= and =vterm=.

I'll give some thoughts from my recent experience using it, especially in Emacs, and we'll kick off a new project so I can show you how it works.

We'll also compare the experience of using Emacs terminal emulators versus what it's like in a "real" one like =foot=, then check out some Emacsp packages that should smooth out the experience.

Let's try out Claude Code in Emacs and write an XMPP client library for Guile!

* The Final Config

We used the following two packages to improve the Claude Code experience in Emacs:

- https://github.com/stevemolitor/claude-code.el
- https://github.com/stevemolitor/monet

#+begin_src emacs-lisp

  (use-package monet
    :vc (:url "https://github.com/stevemolitor/monet" :rev :newest))

  ;; NOTE: This will take a while due to massive GIFs in the repo!
  (use-package claude-code
    :ensure t
    :vc (:url "https://github.com/stevemolitor/claude-code.el" :rev :newest)

    :config
    ;; optional IDE integration with Monet
    (add-hook 'claude-code-process-environment-functions #'monet-start-server-function)
    (monet-mode 1)

    (claude-code-mode)
    :bind-keymap ("C-c c" . claude-code-command-map)

    ;; Optionally define a repeat map so that "M" will cycle thru Claude auto-accept/plan/confirm modes after invoking claude-code-cycle-mode / C-c M.
    :bind
    (:repeat-map my-claude-code-map ("M" . claude-code-cycle-mode)))

#+end_src
