#+title: Can Casual Suite Improve Emacs UI?
#+subtitle: System Crafters Live - August 23, 2024
#+date: [2024-08-23 Fri]
#+video: 0ikuZLRDmhU

* News

- Reminder about the EmacsConf 2024 Call for Participation:

  The conference will be December 7 and 8 this year:

  https://emacsconf.org/2024/cfp/

  If you have an Emacs-related topic you're excited about, consider submitting a proposal!

- Next week (really!): New System Crafters video on workflows for managing many tasks with Org agenda bulk actions!


* Checking out Casual Suite

Today we're going to check out the "Casual" packages for Emacs by Charles Choi.  These packages are intended to provide friendly interfaces for certain Emacs functionality so that they are easier to navigate.

https://github.com/kickingvegas/casual-suite

Here are the (currently) included Casual interfaces:

- Casual I-Search - a Transient menu for I-Search.
- Casual Dired - a Transient porcelain for the Dired file manager.
- Casual Info - a Transient porcelain for Info.
- Casual Calc - a Transient porcelain for Calc.
- Casual IBuffer - a Transient porcelain for IBuffer.
- Casual RE-Builder - a Transient porcelain for RE-Builder.
- Casual Bookmarks - a Transient porcelain for the bookmark list.
- Casual Avy - a Transient porcelain for Avy.

We may actually install and configure these separately, though!
