#+title: Spritely Institute: Building the Future of Decentralized Apps
#+subtitle: System Crafters Live - December 6, 2024
#+date: [2024-12-06 Fri]
#+video: RsW7PWhS_vg

* News

- EmacsConf 2024 is this weekend!

  Lots of great talks are on the schedule here:

  https://emacsconf.org/2024/talks/

  I'm particularly excited about Robin Templeton's talk about the revival of Guile Emacs:

  https://emacsconf.org/2024/talks/guile/

- The Git Good workshop starts this weekend!

  In this workshop, I'll teach you everything you need to know about Git from the basic commands to advanced techniques like =git rebase= and =git cherry-pick=.

  But that's not all: along the way I'll also be teaching you how Git manages everything internally so that you actually understand how it works under the hood.  It's really interesting!

  There are two dates, the first being *this Sunday*, Dec 8th at 09:00 UTC and the next the following Sunday on Dec 15th at 16:00 UTC.

  More information and registration details can be found here:

  https://systemcrafters.net/courses/git-good-workshop/

  If you can't make these dates, keep an eye out for more for January!

  Subscribe to the newsletter to be notified:

  https://systemcrafters.net/newsletter/

- The Spritely Institute is having a fundraiser!

  We will talk about this more with Christine later in the stream, but I did want to call it out right up front:

  https://spritely.institute/donate/

  The Spritely Institute is working hard on new tools and technologies that are very important to the future of the Internet and also the future of Scheme!

  Consider donating on a monthly basis to help them continue working toward these goals so that we can have a more friendly, fun Internet that isn't dominated by corporate interests.

* Interview with Christine Lemmer-Webber!

Today we're chatting with the Executive Director of the Spritely Institute, Christine Lemmer-Webber, about the work that they've been doing over the last couple of years to build a better platform for developing distributed, community-centric apps!

Some topics we'll cover:

- What are Spritely's goals?
- What is Spritely Goblins?
  - What is OCapN?
- What is Spritely Hoot?
- Why Scheme?  Why Guile?
- How will Spritely impact Guix?
- What's coming in 2025 for Guile users?

Christine will also give us a demo of some of the latest work they've been doing around Spritely Goblins!
