#+title: Gnus for Noobs: Mail and News in Emacs
#+subtitle: System Crafters Live - March 28, 2025
#+date: [2025-03-28 Fri]
#+video: I1H1GuPvhCc

[[https://forum.systemcrafters.net/t/gnus-for-noobs-mail-and-news-in-emacs-system-crafters-live/1516][Discuss this stream on the forum!]]

* News

- Lionyx blog post about the emacs-solo stream:

  https://www.rahuljuliato.com/posts/emacs-solo-demo

- Check out Paul (Giacomo / fishinthecalculator) talk about hosting Forgejo in Guix using OCI containers!

  Video is not up yet but will be at https://www.youtube.com/@guix.social-rv9rg

- New Guix Course in Development

  System Crafters Guild members at 15/mo and above will have early access to in-development course material while I'm working on it (on the Forum).

  Join the Guild here:  https://systemcrafters.store

* Let's Learn Gnus!

Here are some notes from the stream:

#+begin_src emacs-lisp

  (setq gnus-select-method '(nnnil ""))

  (setq gnus-secondary-select-methods
        '((nnimap "imap.myserver.com")
          (nntp "gwene" (nntp-address "news.gwene.org"))
          (nnatom "xkcd.com/atom.xml")
          (nntp "news.yhetil.org")))

  (setq nnmail-split-methods
        '(("mail.guix-days" "^Subject:.*Guix Days")))

  ;; Turn on adaptive scoring
  (setq gnus-use-adaptive-scoring t)

  ;; Start the daemon to automatically check email
  (gnus-demon-add-rescan)
  (gnus-demon-init)

#+end_src

Once you have this set up, you can run =M-x gnus= and then press =^= (caret) to see the entire list of news groups for the subscribed RSS feeds.  Press =u= to subscribe to any feed to see it on your main groups screen.

Use =M-g= to refresh groups.

To reply to a newsgroup (or mailing list via nntp) message, use =f=.
