#+title: Hosting Services with Guix Containers
#+subtitle: System Crafters Live - November 10, 2023
#+date: [2023-11-10 Fri]
#+video: QS5MnN_fits

* Updates

- Another experiment!  The primary live chat is now on IRC: =#systemcrafters-live= on =irc.libera-chat=!

- Still working on the Matrix to IRC bridge problem.  Today's stream is one side-effect of my investigations!

* Making Guix Hosting Easier

One big challenge of using Guix to deploy servers to the cloud is that most cloud providers do not provide Guix images so you either have to upload your own or convert another distro to Guix!

Recently it occurred to me, though, that it might be possible to use Guix inside of a common "foreign" distro on a cloud provider.  Both Debian and Alpine have Guix in their package repos, so we'll experiment with one of these distros to see how feasible this idea will be!

There is prior art for hosting services in Guix containers.  [[https://fosstodon.org/@pjotrprins@mastodon.social][Pjotr Prins]] shared this configuration with me:

https://git.genenetwork.org/guix-bioinformatics/tree/gn/services/bnw-container.scm

Let's try to host a few things inside of a Guix container (or containers?)

- Basic website with Nginx
- XMPP server with Prosody
- IRC bouncer with ZNC?
- SSH server?

* Guix Containers vs Docker Compose
